# Copyright (c) 2018 TOYOTA MOTOR CORPORATION
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

#  * Redistributions of source code must retain the above copyright notice,
#  this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#  notice, this list of conditions and the following disclaimer in the
#  documentation and/or other materials provided with the distribution.
#  * Neither the name of Toyota Motor Corporation nor the names of its
#  contributors may be used to endorse or promote products derived from
#  this software without specific prior written permission.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Planner selection
base_global_planner: "navfn/NavfnROS"
#base_local_planner: "dwa_local_planner/DWAPlannerROS"
base_local_planner: base_local_planner/TrajectoryPlannerROS

# Recovery behaviors are defined in robot folders

TrajectoryPlannerROS:
  acc_lim_theta: 0.1
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  angular_sim_granularity: 0.05
  dwa: false
  escape_reset_dist: 0.1
  escape_reset_theta: 1.5707963267948966
  escape_vel: -0.05
  goal_distance_bias: 1
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.1
  holonomic_robot: true
  max_vel_theta: 0.2
  max_vel_x: 0.2
  min_in_place_vel_theta: 0.2
  min_vel_theta: -0.05
  min_vel_x: 0.05
  min_vel_y: 0.05
  occdist_scale: 0.01
  oscillation_reset_dist: 0.1
  path_distance_bias: 0.4
  restore_defaults: false
  sim_granularity: 0.05
  sim_time: 1.0
  simple_attractor: false
  vtheta_samples: 20
  vx_samples: 20
  y_vels: -0.3,-0.1,0.1,-0.3



resolution: 0.05
inflation_radius: 0.35
transform_tolerance: 3
path_distance_bias: 1

# Oscillation
oscillation_timeout: 10.0
oscillation_distance: 0.5

# Global planner
planner_frequency: 0.0
planner_patience: 1.0
NavfnROS:
  allow_unknown: true  # TODO: investigate this
  default_tolerance: 0.0
  # do not restrict planner
  planner_window_x: 0.0
  planner_window_y: 0.0
  # debug
  visualize_potential: false

# Local planner
controller_frequency: 10.0
controller_patience: 5.0
aggressive_reset:
  reset_distance: 1.84
  
DWAPlannerROS:
  acc_lim_theta: 0.1
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  angular_sim_granularity: 0.05
  dwa: false
  escape_reset_dist: 0.1
  escape_reset_theta: 1.5707963267948966
  escape_vel: -0.05
  goal_distance_bias: 1
  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.1
  holonomic_robot: true
  max_vel_theta: 0.2
  max_vel_x: 0.2
  min_in_place_vel_theta: 0.2
  min_vel_theta: -0.05
  min_vel_x: 0.05
  min_vel_y: 0.05
  occdist_scale: 0.01
  oscillation_reset_dist: 0.1
  path_distance_bias: 0.4
  restore_defaults: false
  sim_granularity: 0.05
  sim_time: 1.0
  simple_attractor: false
  vtheta_samples: 20
  vx_samples: 20
  y_vels: -0.3,-0.1,0.1,-0.3